import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';

//コンポーネント
import StyledComponentsRegistry from '@/libs/styled-components-registry';
import { Header } from '@/components/common/Header';
import { Footer } from '@/components/common/Footer';
import { Nav } from '@/components/common/Nav'; //追従するナビゲーション

const notoSans = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${notoSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StyledComponentsRegistry>
          <Header />
          <Nav />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
